#Minecraft server properties
#Thu Nov 13 10:23:41 UTC 2025
accepts-transfers=false
allow-flight=false
allow-nether=true
broadcast-console-to-ops=false
broadcast-rcon-to-ops=true
bug-report-link=
debug=false
difficulty=normal
enable-code-of-conduct=false
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=true
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=0dRJTrNu9XZ2tGTpsVESBrKaVmFzx7rcx7EUL2bT
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-build-height=256
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=60000
max-world-size=29999984
motd=\u00C2\u00A74\u00C2\u00A7k||||\u00C2\u00A7r \u00C2\u00A7c\u00C2\u00A7lS\u00C2\u00A76\u00C2\u00A7lI\u00C2\u00A7e\u00C2\u00A7lG\u00C2\u00A7a\u00C2\u00A7lM\u00C2\u00A7b\u00C2\u00A7lA \u00C2\u00A7d\u00C2\u00A7lServer \u00C2\u00A75\u00C2\u00A7lMC \u00C2\u00A72\u00C2\u00A7k||||\u00C2\u00A7r\n\u00C2\u00A7c\u00C2\u00A7l\u00C3\u0099\u00C2\u0085\u00C2\u00A76\u00C2\u00A7l\u00C3\u0098\u00C2\u00B1\u00C2\u00A7e\u00C2\u00A7l\u00C3\u0098\u00C2\u00AD\u00C2\u00A7a\u00C2\u00A7l\u00C3\u0098\u00C2\u00A8\u00C2\u00A7b\u00C2\u00A7l\u00C3\u0098\u00C2\u00A7 \u00C2\u00A7d\u00C2\u00A7l\u00C3\u0098\u00C2\u00A8\u00C2\u00A75\u00C2\u00A7l\u00C3\u0099\u00C2\u0083\u00C2\u00A7c\u00C2\u00A7l\u00C3\u0099\u00C2\u0085
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=ahmedger1
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=3
snooper-enabled=true
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=50
status-heartbeat-interval=0
sync-chunk-writes=false
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=4
white-list=false
