bind = "0.0.0.0:25577"
motd = "A Velocity Server"
show-max-players = 500

[servers]
lobby = "127.0.0.1:25565"
try = ["lobby"]

[forced-hosts]

[advanced]
compression-threshold = 256
compression-level = -1
login-ratelimit = 3000

[query]
enabled = false
