name: Minecraft Infinite Loop (Safe)

on:
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'

      - name: Download Paper 1.16.5
        run: |
          curl -L -o server.jar \
          https://api.papermc.io/v2/projects/paper/versions/1.16.5/builds/794/downloads/paper-1.16.5-794.jar

      - name: Install performance libs
        run: sudo apt-get update && sudo apt-get install -y libjemalloc-dev

      - name: Run server (5.5h)
        run: |
          export MALLOC_ARENA_MAX=2
          export LD_PRELOAD=$(dpkg -L libjemalloc-dev | grep '\.so$' | head -n1)
          java -Xmx16G -Xms12G \
          -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 \
          -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC \
          -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 \
          -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 \
          -jar server.jar --nogui &
          SERVER_PID=$!
          sleep 19800
          echo stop | nc -N localhost 25565 || kill $SERVER_PID
          wait $SERVER_PID || true

      - name: Check if anything changed
        id: changed
        run: |
          git add world/ plugins/
          if git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit & push (only if changed)
        if: steps.changed.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git commit -m "Save $(date -u)"
          git pull --rebase --autostash https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push

      - name: Wait 10s cooldown
        run: sleep 10

      - name: Retrigger same workflow (if no run queued)
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          runs=$(gh run list --workflow=minecraft-infinite-loop-safe.yml --json status -q '.[] | select(.status=="queued" or .status=="in_progress") | .status' | wc -l)
          if [ "$runs" -le 1 ]; then
            gh workflow run minecraft-infinite-loop-safe.yml
          else
            echo "Another run already queued, skipping retrigger."
          fi
